### PR TITLE
small changes to get it build

### PR DESCRIPTION
**Pull request by transistorgit**
Set<T> was undefined, CGFloat Array wrong type

Had some initial build problems. I’m new to iOS and xcode, so maybe its my fault, but I think the project should build out of the box. That’s what my changes should provide.

### CODE REVIEW

**Comment by zemirco** [comment]
Which Xcode version are you using?

**Comment by transistorgit** [comment]
Xcode 6.1.1

**Comment by zemirco** [comment]
Please use latest version (Xcode 6.3 beta 2).

**Comment by transistorgit** [comment]
OK, with Xcode 6.3 beta 2 it's working without my changes. (I used the official version so far)

**Pull request closed without merging**
